services:
  # Laravel Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project_management_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8080:8000"
    environment:
      - DB_HOST=db
      - DB_DATABASE=project_management
      - DB_USERNAME=laravel
      - DB_PASSWORD=laravel123
    depends_on:
      - db
    networks:
      - project_network

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: project_management_db
    restart: unless-stopped
    ports:
      - "33060:3306"
    environment:
      MYSQL_DATABASE: project_management
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel123
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - project_network

networks:
  project_network:
    driver: bridge

volumes:
  db_data: